name: Create Feature Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Create a branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        # Convert ISSUE_TITLE to snake_case
        SNAKE_CASE_TITLE=$(echo $ISSUE_TITLE | sed -E 's/([A-Z])/_\1/g' | tr -s '_' | tr '[:upper:]' '[:lower:]' | sed 's/[ -]/_/g' | sed 's/^_//')
        BRANCH_NAME="feature/$ISSUE_NUMBER/$SNAKE_CASE_TITLE"
        
        echo "Creating branch $BRANCH_NAME"
        
        git checkout -b "$BRANCH_NAME"
        git push origin "$BRANCH_NAME"

    - name: Add branch to the issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        # Convert ISSUE_TITLE to snake_case again for the comment
        SNAKE_CASE_TITLE=$(echo ${{ github.event.issue.title }} | sed -E 's/([A-Z])/_\1/g' | tr -s '_' | tr '[:upper:]' '[:lower:]' | sed 's/[ -]/_/g' | sed 's/^_//')
        BRANCH_NAME="feature/$ISSUE_NUMBER/$SNAKE_CASE_TITLE"
        gh issue comment $ISSUE_NUMBER --body "Branch created: $BRANCH_NAME"
