name: Create Branch and Draft PR for Issue

on:
  issues:
    types: [opened]

jobs:
  create_and_associate_branch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config --global user.email "maitenarivero99@gmail.com"
        git config --global user.name "Mai-Ri"

    - name: Create a branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        # Convert ISSUE_TITLE to snake_case properly
        SNAKE_CASE_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g' | sed 's/^_//;s/_$//')
        BRANCH_NAME="feature/$ISSUE_NUMBER/$SNAKE_CASE_TITLE"
        
        echo "Creating branch $BRANCH_NAME"
        
        git checkout -b "$BRANCH_NAME"
        
        # Add an empty commit to ensure the branch has at least one commit
        git commit --allow-empty -m "chore: initialize branch for issue #$ISSUE_NUMBER"
        
        git push origin "$BRANCH_NAME"
        echo "Branch $BRANCH_NAME created and pushed."

    - name: Comment on Issue with Branch Info
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        SNAKE_CASE_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g' | sed 's/^_//;s/_$//')
        BRANCH_NAME="feature/$ISSUE_NUMBER/$SNAKE_CASE_TITLE"
        COMMENT="The branch \`$BRANCH_NAME\` has been created. You can check it out with the following commands:"
        COMMENT+="\n\n\`\`\`bash"
        COMMENT+="\ngit fetch origin"
        COMMENT+="\ngit checkout $BRANCH_NAME"
        COMMENT+="\n\`\`\`"
        gh issue comment $ISSUE_NUMBER --body "$COMMENT"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for the gh command
    


    - name: Create Draft Pull Request
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        BRANCH_NAME="feature/$ISSUE_NUMBER/$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g' | sed 's/^_//;s/_$//')"

        # Confirm the body of the PR is correctly set
        PR_BODY="closes #$ISSUE_NUMBER"
        echo "PR body: $PR_BODY"

        # Create a draft pull request targeting 'develop' branch
        gh pr create --draft --base develop --head "$BRANCH_NAME" --title "$ISSUE_TITLE" --body "$PR_BODY"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for the gh command
