name: Create and Associate Branch with Issue

on:
  issues:
    types: [opened]

jobs:
  create_and_associate_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Create a branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        # Convert ISSUE_TITLE to snake_case
        SNAKE_CASE_TITLE=$(echo $ISSUE_TITLE | sed -E 's/([A-Z])/_\1/g' | tr -s '_' | tr '[:upper:]' '[:lower:]' | sed 's/[ -]/_/g' | sed 's/^_//')
        BRANCH_NAME="feature/$ISSUE_NUMBER/$SNAKE_CASE_TITLE"
        
        echo "Creating branch $BRANCH_NAME"
        
        git checkout -b "$BRANCH_NAME"
        git push origin "$BRANCH_NAME"

    - name: Add branch to the issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        # Convert ISSUE_TITLE to snake_case again for the comment
        SNAKE_CASE_TITLE=$(echo ${{ github.event.issue.title }} | sed -E 's/([A-Z])/_\1/g' | tr -s '_' | tr '[:upper:]' '[:lower:]' | sed 's/[ -]/_/g' | sed 's/^_//')
        BRANCH_NAME="feature/$ISSUE_NUMBER/$SNAKE_CASE_TITLE"
        gh issue comment $ISSUE_NUMBER --body "Branch created: $BRANCH_NAME"

    - name: Get issue details
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        echo "Getting details for Issue Number: $ISSUE_NUMBER"
        gh issue view $ISSUE_NUMBER --json title,state -q .state > issue_state.txt
        ISSUE_STATE=$(cat issue_state.txt)
        echo "Issue State: $ISSUE_STATE"

        if [ "$ISSUE_STATE" != "open" ]; then
          echo "Issue #$ISSUE_NUMBER is not open. Skipping association."
          exit 0
        fi

    - name: Associate branch with issue
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        BRANCH_NAME=${{ github.ref_name }}
        echo "Associating Branch: $BRANCH_NAME with Issue: $ISSUE_NUMBER"
        gh issue comment $ISSUE_NUMBER --body "Branch $BRANCH_NAME has been created and associated with this issue."

    - name: Mark issue as in progress
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        echo "Marking Issue #$ISSUE_NUMBER as 'in progress'"
        gh issue edit $ISSUE_NUMBER --add-label "in progress"
