name: Python Metrics, Linting, and Dependency Analysis

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 radon safety pip-audit

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Calculate Cyclomatic Complexity
      run: |
        radon cc . -s -a

    - name: Calculate Lines of Code
      run: |
        pip install cloc
        cloc .

    - name: Analyze Dependencies with Safety
      run: |
        safety check

    - name: Audit Dependencies with pip-audit
      run: |
        pip-audit
